"""Render a plain-English cleaning report from the plan + change log.

Today this is a deterministic template. After fine-tuning, the model can narrate
this more naturally (Field Notes / report-narrator role) — but the template is a
fine fallback and keeps the trust contract (every change explained).
"""

from __future__ import annotations


def render_report(plan: dict, change_log: list[dict],
                  before: dict, after: dict) -> str:
    lines: list[str] = []
    lines.append("# 🧽 Cleaning report\n")
    lines.append(f"**{plan.get('dataset_summary', '')}**\n")

    src = "🤖 fine-tuned model" if plan.get("_generated_by") != "mock_planner" \
        else "🧩 heuristic planner (model not wired yet)"
    lines.append(f"_Plan generated by: {src}._\n")

    # Headline before/after.
    lines.append("## At a glance")
    lines.append(f"- Rows: **{before['n_rows']} → {after['n_rows']}**")
    lines.append(f"- Columns: **{before['n_cols']} → {after['n_cols']}**")
    total_cells = sum(e.get("cells_changed", 0) for e in change_log if e["scope"] == "column")
    lines.append(f"- Cells changed: **{total_cells}**\n")

    # Table-level.
    table = [e for e in change_log if e["scope"] == "table"]
    if table:
        lines.append("## Structural fixes")
        for e in table:
            lines.append(f"- `{e['op']}` — {e['detail']}")
        lines.append("")

    # Column-level.
    cols = [e for e in change_log if e["scope"] == "column" and e.get("cells_changed", 0) > 0]
    if cols:
        lines.append("## Column fixes")
        for e in cols:
            why = f" — {e['rationale']}" if e.get("rationale") else ""
            lines.append(f"- **{e['column']}** · `{e['op']}` "
                         f"({e['cells_changed']} cells){why}")
        lines.append("")

    # Surfaced canonicalization mappings (the AI-headline feature — show them!).
    maps = [(c["name"], op["mapping"])
            for c in plan.get("columns", [])
            for op in c.get("operations", [])
            if op["op"] == "canonicalize_categories" and op.get("mapping")]
    if maps:
        lines.append("## Value mappings applied")
        for cname, mapping in maps:
            lines.append(f"**{cname}:**")
            for raw, canon in mapping.items():
                lines.append(f"- `{raw}` → `{canon}`")
        lines.append("")

    # Flags (model populates; mock leaves empty).
    flags = plan.get("flags", [])
    if flags:
        lines.append("## ⚠️ Flagged for your review (not changed)")
        for f in flags:
            lines.append(f"- **{f.get('column')}** {f.get('row_hint', '')} — "
                         f"{f.get('issue')}: {f.get('rationale', '')}")
        lines.append("")

    lines.append("---\n_Original file untouched. Review the changes above before using._")
    return "\n".join(lines)
